# Generated by Django 4.1.7 on 2023-03-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexeSportif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=250)),
                ('lattitude', models.DecimalField(decimal_places=20, max_digits=22)),
                ('longtitude', models.DecimalField(decimal_places=20, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Complexe.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('typeT', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('tarifT', models.CharField(max_length=250)),
                ('complexeSportif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Complexe.complexesportif')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Complexe.terrain')),
            ],
        ),
        migrations.AddField(
            model_name='complexesportif',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Complexe.zone'),
        ),
    ]
